version: '3'

services:
  server:
    build: .
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://ganshmuel:1234@mysql/billdb
    depends_on:
      - mysql
    volumes:
      - ./in:/in  # Mount the /in directory as a host volume
    command: sh -c "sleep 20 && python server.py"
    restart: on-failure

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: billdb
      MYSQL_USER: ganshmuel
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql-data/db:/var/lib/mysql
      - ./billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql  # Mount the SQL file
    command: --init-file=/docker-entrypoint-initdb.d/billingdb.sql  # Specify init file

networks:
  default:

volumes:
  mysql-data: